### ISSUE TITLE
Control DYNAMIXEL servo

### ISSUE THREAD

**Issue by owenpark8** [umrover/mrover-ros2#37]
[DYNAMIXEL Servo](https://www.robotis.us/dynamixel-xl330-m288-t/)
[DYNAMIXEL Shield](https://www.robotis.us/dynamixel-shield-for-arduino-mkr-series/)
[Arduino MKR Wifi 1010](https://store-usa.arduino.cc/collections/mkr-family/products/arduino-mkr-wifi-1010)

Manuals:
- [DYNAMIXEL Shield for Arduino MKR](https://emanual.robotis.com/docs/en/parts/interface/mkr_shield/)

Control the servo to be able to do 45 degree rotations in a circle.

**Comment by jamessou1** [comment]
Pushed to embedded branch
