### ISSUE TITLE
Receive CAN FD messages on STM32 Nucleo

### ISSUE THREAD

**Issue by owenpark8** [umrover/mrover-ros2#49]
Use fdcanusb from laptop to send message to NUCLEO-G431RB with CAN FD transceiver (ISO1044DEVM). CAN bus should be at 1 Mbps nominal / 5 Mbps data. Should be able to see message reception on Nucleo with breakpoint on HAL_FDCAN_RxFifo0Callback().

**Comment by artyom-boyarov** [comment]
### Nov 21
Sent messages from one nucleo to another. The boards were connected to CAN transceivers and with a proper CAN bus (so CANH/CANL lines)

**Comment by artyom-boyarov** [comment]
## Dec 3
Successfully received messages sent through FDCAN-USB. 
### Setup
#### Sender laptop side
Connect FDCAN-USB to CAN transceiver. Wires are black = ground, green = low, blue = high. Connect transceiver VCC to 5V on an STM32 plugged into the **sender** laptop. Run the following commands:
`sudo ip link add name can1 type vcan`
(in new terminal)
`mrover`
`sudo ./ansible/roles/esw/files/bin/fdcanusb_daemon -F -v /dev/fdcanusb can1`
To send messages run:
`cansend <HEX ID>##<1-digit HEX flags><message>`
e.g.
`cansend 011##01234`

#### Receiver laptop side
Plug in STm32 and connect TX to transceiver TX, RX to transceiver RX, ditto for 5V and GND. Run.

Works in both bus monitoring and normal mode.
